Feature/fix eslint rules
guimochila/tracker pull request #8
Opened 2019-09-06 13:59 UTC by Marlon-Santos

2019-09-07 16:34 UTC, guimochila requested changes
As we are not fully working on the app, just do the changes I mentioned. We will be fixing the issues gradually.

2019-09-07 16:34 UTC, guimochila commented on packages/app/src/context/createDataContext.jsx
> +    actions.forEach((element, index) => {
Aqui as regras que dão error são: guard-for-in e no restricted-syntax. Nesse caso olhando as documentações do Eslint (https://eslint.org/docs/rules/guard-for-in e https://eslint.org/docs/rules/no-restricted-syntax) podemos melhorar mto o código em desabilitar nenhuma regra. Isso seria melhor:

` Object.keys(actions).forEach(key => {
      boundActions[key] = actions[key](dispatch);
    });`

2019-09-07 16:34 UTC, guimochila commented on packages/app/src/api/tracker.js
> +      newConfig.headers.Authorization = `Bearer ${token}`;
Aqui é melhor desabilitar a regra somente para essa linha:

`// eslint-disable-rule-next-line no-param-reassign`

Aqui nao se pode modificar config com newConfig. Veja que a função retorna config e nao newConfig.. e esse config faz parte de como funciona axios. Está na documentação: https://github.com/axios/axios, veja na parte de Interceptors.

2019-09-08 14:10 UTC, guimochila commented
I think is better we resolve the eslint issues as we advance in the app. What do you think @Marlon-Santos ?

2019-09-09 21:38 UTC, Marlon-Santos commented
> Eu acho que é melhor resolvermos os problemas de exclusão à medida que avançamos no aplicativo. O que você acha @ Marlon-Santos ?

I agree with you

2019-09-10 04:47 UTC, closed without merging